module "adb" {
  source                              = "git::ssh://git@ssh.dev.azure.com/v3/Axpo-AXSO/TIM-INFRA-MODULES/azurerm_databricks?ref=~{gitRef}~"
  location                            = var.location
  resource_group_name                 = var.resource_group_name
  subscription                        = var.subscription
  project_name                        = var.project_name
  environment                         = var.environment
  identity_type                       = var.identity_type
  umids_names                         = var.umids_names
  virtual_network_resource_group_name = var.virtual_network_resource_group_name
  virtual_network_name                = var.virtual_network_name
  public_subnet_name                  = var.public_subnet_name
  private_subnet_name                 = var.private_subnet_name
  pe_subnet_name                      = var.pe_subnet_name
  key_vault_name                      = var.key_vault_name
  sku                                 = var.sku
  frotend_private_access_enabled      = var.frotend_private_access_enabled
  storage_account_sku_name            = var.storage_account_sku_name
}
